UPDATE products SET
  owner_id = NULL,
  name = 'Plantilla Presentación Empresa',
  brand = 'Verta Studio',
  category = 'plantillas',
  price = 11990,
  old_price = 16990,
  rating = 0,
  reviews = 0,
  stock = 0,
  badge = 'popular',
  description = 'Presentación corporativa de 24 diapositivas editable en PowerPoint y Google Slides. Diseño verde premium con gráficos e iconos incluidos.',
  features = '["24 diapositivas","PPTX + Google Slides","Gráficos e iconos incluidos","Relación 16:9"]',
  file_type = 'PPTX',
  file_size = '18 MB',
  compatibility = 'PowerPoint 2016+ · Google Slides',
  license = 'Uso personal y comercial',
  downloads = 2290,
  includes = '["Archivo .pptx","Enlace a Google Slides","Guía de uso"]',
  requirements = '["PowerPoint o Google Slides"]',
  updates = 'Actualizaciones de por vida',
  support = 'Soporte por correo 15 días',
  image = 'https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=800',
  images = '["https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=800","https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=800"]',
  product_code = 'VT-PLANTILLAP',
  status = 'active'
WHERE slug = 'plantilla-presentacion-empresa';

UPDATE products SET
  owner_id = NULL,
  name = 'Verta Display — Títulos',
  brand = 'Verta Type',
  category = 'fuentes',
  price = 13990,
  old_price = 19990,
  rating = 0,
  reviews = 0,
  stock = 0,
  badge = NULL,
  description = 'Tipografía display de alto contraste para titulares y branding. 4 pesos + itálicas, perfecta para campañas y editorial.',
  features = '["4 pesos + itálicas","Alto contraste","Titulares impactantes","Licencia comercial"]',
  file_type = 'OTF',
  file_size = '2.5 MB',
  compatibility = 'Windows · macOS · Linux · Web',
  license = 'Uso personal y comercial',
  downloads = 1120,
  includes = '["8 archivos .otf","Muestra PDF"]',
  requirements = '["Cualquier software de diseño"]',
  updates = 'Actualizaciones de por vida',
  support = 'Soporte por correo 15 días',
  image = 'https://images.pexels.com/photos/4012966/pexels-photo-4012966.jpeg?auto=compress&cs=tinysrgb&w=800',
  images = '["https://images.pexels.com/photos/4012966/pexels-photo-4012966.jpeg?auto=compress&cs=tinysrgb&w=800"]',
  product_code = 'VT-FUENTEVERT',
  status = 'active'
WHERE slug = 'fuente-verta-display';
